default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 12345

development:
  <<: *default
  database: q_dev

test:
  <<: *default
  database: q_test

production:
  <<: *default
  database: q_pro